// Generated by scripts/src/generate-demo-library.mjs. Regenerate rather than editing.
export type DemoId = string;

export type DemoDefinition = {
  id: DemoId;
  title: string;
  subtitle: string;
  description: string;
  category: string;
  partCount: number;
  jointCount: number;
  highlights: string[];
  learningTip: string;
  accent: string;
};

export const DEMOS: DemoDefinition[] = [
  {
    "id": "windmill",
    "title": "Windmill",
    "subtitle": "Your first moving assembly",
    "category": "Start here",
    "accent": "#66cfbd",
    "description": "The original two-part demo: a grounded post and a rotor. See how one revolute mate turns a model into motion.",
    "highlights": [
      "2 parts",
      "30 RPM drive",
      "One revolute mate"
    ],
    "learningTip": "Press Play, then change the rotor mate's RPM. Stop returns the assembly to its starting pose.",
    "partCount": 2,
    "jointCount": 1
  },
  {
    "id": "orrery",
    "title": "Solar-system orrery",
    "subtitle": "Thirteen bodies in concert",
    "category": "Showcase",
    "accent": "#a699f2",
    "description": "The original planetary showcase, with eight orbital arms, three nested moons and an independently driven asteroid ring.",
    "highlights": [
      "13 bodies",
      "Nested motion",
      "12 motorised mates"
    ],
    "learningTip": "Follow a moon's mate to its planet: its motion combines two driven joints. Speeds are illustrative, not astronomical.",
    "partCount": 13,
    "jointCount": 12
  },
  {
    "id": "gyroscope",
    "title": "Three-axis driven gimbal",
    "subtitle": "Explore supported nested rotation",
    "category": "Motion",
    "accent": "#e2be76",
    "description": "Nested rings carry a steel flywheel through bored bearing housings and visible shafts. Three motors drive the intersecting axes.",
    "highlights": [
      "Three driven axes",
      "Shafts and bearings",
      "Mixed materials"
    ],
    "learningTip": "Try changing one joint's RPM at a time. This is a powered gimbal study in zero gravity, not a passive gyroscope prediction.",
    "partCount": 4,
    "jointCount": 3
  },
  {
    "id": "kinetic-mobile",
    "title": "Kinetic mobile",
    "subtitle": "A small moving sculpture",
    "category": "Motion",
    "accent": "#72b5df",
    "description": "A brass crown carries two turning branches and four medallions. Different motor speeds create a layered moving sculpture.",
    "highlights": [
      "7 driven joints",
      "Branching assembly",
      "Counter-rotation"
    ],
    "learningTip": "Watch the crown, branches and medallions turn at different rates. Each joint is motor-driven; gravity is off.",
    "partCount": 8,
    "jointCount": 7
  },
  {
    "id": "material-studio",
    "title": "Material studio",
    "subtitle": "One shape, eight materials",
    "category": "Materials",
    "accent": "#c5cf93",
    "description": "Compare eight engineering materials on the same bored-boss shape. Inspect the sketches, additive features and through cuts.",
    "highlights": [
      "8 materials",
      "Editable feature chains",
      "Add and subtract"
    ],
    "learningTip": "Select a sample to compare its material and mass. Expand its features to edit the boss or bore. Display mounts are fixed.",
    "partCount": 9,
    "jointCount": 8
  }
];

export function getDemo(id: DemoId): DemoDefinition | undefined {
  return DEMOS.find((demo) => demo.id === id);
}
