// Generated by scripts/src/generate-demo-library.mjs. Regenerate rather than editing.
export type DemoId = string;

export type DemoDefinition = {
  id: DemoId;
  title: string;
  subtitle: string;
  description: string;
  category: string;
  partCount: number;
  jointCount: number;
  highlights: string[];
  learningTip: string;
  accent: string;
};

export const DEMOS: DemoDefinition[] = [
  {
    "id": "windmill",
    "title": "Windmill",
    "subtitle": "Your first moving assembly",
    "category": "Start here",
    "accent": "#66cfbd",
    "description": "The original two-part demo: a grounded post and a rotor. See how one revolute mate turns a model into motion.",
    "highlights": [
      "2 parts",
      "30 RPM drive",
      "One revolute mate"
    ],
    "learningTip": "Press Play, then change the rotor mate's RPM. Stop returns the assembly to its starting pose.",
    "partCount": 2,
    "jointCount": 1
  },
  {
    "id": "orrery",
    "title": "Solar-system orrery",
    "subtitle": "Thirteen bodies in concert",
    "category": "Showcase",
    "accent": "#a699f2",
    "description": "The original planetary showcase, with eight orbital arms, three nested moons and an independently driven asteroid ring.",
    "highlights": [
      "13 bodies",
      "Nested motion",
      "12 motorised mates"
    ],
    "learningTip": "Follow a moon's mate to its planet: its motion combines two driven joints. Speeds are illustrative, not astronomical.",
    "partCount": 13,
    "jointCount": 12
  },
  {
    "id": "gyroscope",
    "title": "Three-axis driven gimbal",
    "subtitle": "Explore supported nested rotation",
    "category": "Motion",
    "accent": "#e2be76",
    "description": "Nested rings carry a steel flywheel through bored bearing housings and visible shafts. Three motors drive the intersecting axes.",
    "highlights": [
      "Three driven axes",
      "Shafts and bearings",
      "Mixed materials"
    ],
    "learningTip": "Try changing one joint's RPM at a time. This is a powered gimbal study in zero gravity, not a passive gyroscope prediction.",
    "partCount": 4,
    "jointCount": 3
  },
  {
    "id": "kinetic-mobile",
    "title": "Kinetic mobile",
    "subtitle": "A small moving sculpture",
    "category": "Motion",
    "accent": "#72b5df",
    "description": "A brass crown carries two turning branches and four medallions. Different motor speeds create a layered moving sculpture.",
    "highlights": [
      "7 driven joints",
      "Branching assembly",
      "Counter-rotation"
    ],
    "learningTip": "Watch the crown, branches and medallions turn at different rates. Each joint is motor-driven; gravity is off.",
    "partCount": 8,
    "jointCount": 7
  },
  {
    "id": "material-studio",
    "title": "Material force lab",
    "subtitle": "Same force, different mass",
    "category": "Physics",
    "accent": "#c5cf93",
    "description": "Give eight identical shapes the same force for two seconds. Watch lighter materials accelerate faster and compare measured results with F = ma.",
    "highlights": [
      "8 materials",
      "Measured acceleration",
      "Two-second experiment"
    ],
    "learningTip": "Try simulation, choose 0.5 or 1 millinewton, then press Run experiment. The result holds after two seconds. Ideal guides; gravity and friction are off.",
    "partCount": 9,
    "jointCount": 8
  },
  {
    "id": "stewart-platform",
    "title": "Stewart platform",
    "subtitle": "Six actuators. One moving deck.",
    "category": "Engineering",
    "accent": "#ecab76",
    "description": "Six telescopic actuators close a network of 18 joints around one payload deck. Inspect the bored barrels, turned rods and spherical ends, then run a coordinated lift.",
    "highlights": [
      "14 rigid bodies",
      "18 coupled joints",
      "Closed-loop mechanism"
    ],
    "learningTip": "Six linear motors extend at 2 mm/s for six seconds, then hold. The lift is checked against leg-length geometry. Ideal bearings and drives; this demo does not command all six axes.",
    "partCount": 14,
    "jointCount": 18
  }
];

export function getDemo(id: DemoId): DemoDefinition | undefined {
  return DEMOS.find((demo) => demo.id === id);
}
